export default {
  RECYCLE: "Recycle",
  HOW_TO_RECYCLE: "How To Recycle",
  ECOREWARD: "Eco Reward",
  HISTORY: "History",
  RECYCLEORDER: "Recycle Order",
  SETTING: "Settings",
  HOME: "Home",
  NOTIFICATIONS: "Notifications",
  PROFILE: "Profile",
  CONTACTUS: "Contact us",
  LANGUAGES: "Languages",
  SPANISH: "Español",
  ENGLISH: "English",
  SECURITYSETTING: "Security Setting",
  CHANGEPASSWORD: "Change Password",
  DELETEACCOUNT: "Delete Account",
  PRIVACYPOLICY: "Privacy Policy",
  TERMCONDITONS: "Terms Conditions",
  LOGOOUT: "Logout",
  ADDREQUEST: "Add Request",
  CHOOSERECYCLEITEM: "Choose Recycle Items",
  NEXT: "Next",
  MARKSCHEDULE: "Mark Schedule",
  SCHEDULE: "Schedule",
  ONCEONLY: "Once Only",
  MULTIPLEDATES: "Multiple Dates",
  MONTHLY: "Monthly",
  ONCEONLYSCHEDULE: "Once Only Schedule",
  ONCEONLYDESC:
    "You can Select one schedule on per day either morning or evening.",
  DAY: "Day",
  SELECTSHIFT: "Select Shift",
  SELECTSHIFTSLOT: " Select Shift Slot",
  MORNING: "Morning",
  EVENING: "Evening",
  SELECTDATESHIFT: "Select Date & Shift",
  SELECTSTARTENDTIME: "Select Start and End Time",
  PICKUPADDRESSLOCATION: "Pickup Address & Location",
  UPLOADIMG: "Upload Image",
  NOTES: "Notes",
  THISISDUMMYTXT: "This is the Dummy Text",
  PICKUPREQLOCATION: "Pickup Request Location",
  HI: "Hi",
  WELCOMEBACK: "Welcome Back,",
  SAVE: "Save",
  ORDERCONFIRAMTION: "Order Confirmation",
  CONFIRMORDER: "Confirm Order",
  SELECTEDITEMS: "Selected Items",
  PICKUPTIME: "Pickup Time",
  DATE: "Date",
  CONFIRMORDERMODALDESC:
    "Your disposal request generated & sent to admin successfully,get back to you shortly.",
  THANKYOU: "Thankyou!",
  MULTIPLEDATESSCHEDULE: "Multiple Dates Schedule",
  MULTIPLEDESC:
    "You can Select schedule for two days either morning or evening.",
  PLEASESELECTDATETIME: "Please select Date & Time",
  SELECTMORNINGSTARTENDTIME: "Select Morning Start and End Time",
  MONTHLYSCHEDULE: "Monthly Schedule",
  MONTHLYDESC:
    "You can Select upto 31 dates schedule for month either morning or evening.",
  SETDATE: "Set Date",
  PLEASESELECTSTARTEND: "Please Select Start and End Time",
  RECYCLEYOURMULTIPLE: "Recycle your multiple",
  PRODUCTSWITH: "Products with.",
  ECOREWARD: "ECO Reward",
  EARNEDPOINTS: "Earned Points",
  BALANCE: "Balance",
  CLAIMREWARD: "Claim Reward",
  CLAIMTHEREWARD: "Claim the Reward",
  ENTERCALIMREWARD: "Enter £ to Claim Reward",
  DONATE: "Donate",
  DONATEREWARD: "Enter £ to Donate",
  REDEEM: "Redeem",
  CLAIMMODAL:
    "The minimum redeem amount is 10 €, or more with multiplies of 5€ only.",
  DONATEMODAL:
    "Donate to help the non-profit organizations that cares about the environment.",
  REDEEMPOPUPDESC:
    "Please check all entered information is correct before redeeming this amount.",
  GOBACK: "Go Back",
  CONTINUE: "Continue",
  SUCCESSREDEEMMODALDESC:
    " Your request for redeeming these points is forward successfully.",
  ENOUGHBALANCE: "Not Enough Balance",
  RECEIVEASMALL: "Receive a small",
  THANKYOUFOREFFOR: "thank you for your efforts!",
  REDEEMPOINTS: "Redeem Points",
  DONATE: "Donate",
  RECYCLED: "Recycled",
  FILTER: "Filter",
  CLEARFILTER: "Clear Filter",
  SUBMITCO:'Submit',
  SELECTADATE: "Select a date",
  TOTALEARNEDPOINTS: "Total Earned Points",
  SELECTDATE: "Select Date",
  EDIT: "Edit",
  DELETE: "Delete",
  NONOTIFICATIONYET: "No Notifications Yet",
  LOADMORE: "Load More",
  EMAIL: "Email",
  MOBILENO: "Mobile Number",
  PHONENO: "Phone Number",
  PHONE: "Phone",
  BUSINESSNAME: "Business Name",
  BUSINESSDEATILS: "Business Details",
  LICENSECODE: "License Code (CIF, DNI, NIF)",
  POSTOFFICECODE: "Post Office Code",
  ADDRESSANDLCOATION: "Address & Location",
  BUSINESSCATEGORY: "Business Category",
  STAFFINCHARGE: "Staff Incharge",
  BANKNAME: "Bank Name",
  ACCOUNTTYPE: "Account Type",
  ACCOUNTINFORMATION: "Account Information",
  ACCOUNTHOLDERNAME: "Account Holder Name",
  EDITPROFILE: "Edit Profile",
  FIRSTNAME: "FirstName",
  LASTNAME: "LastName",
  UPDATEPROFILE: "Update Profile",
  UPDATELICENSEIMG: "Update License Image",
  OTHERSTAFF: "Other Staff InCharge",
  IBAN: "IBAN",
  CONTACTUS: "Contact Us",
  FEELFREE: "Feel free to contact Us for your",
  CONVENIENCE: "Convenience",
  CHANGEPASSWORD: "Change Password?",
  ENTERNEWPASSWORDTORESET: "Enter new password to reset.",
  NEWPASSWORD: "New Password",
  CONFIRMNEWPASSWORD: "Confirm New Password",
  CONFIRMPASSWORD: "Confirm Password",
  SUBMIT: "Submit",
  DELETEACCOUNTDES:
    "If you dont have any recycle request, you can delete account.",
  REASONTODELETE: "(Reason to delete account)",
  DELETEMYACCOUNT: "Delete My Account",
  PRIVACYPOLICY: "Privacy Policy",
  TERMSCONDITION: "Terms & Conditions",
  HELLO: "Hello",
  ENTERYOUREMAIL: "Enter your Email",
  FORGOTPASSWORD: "Forgot Password?",
  LOGIN: "Login",
  DONTHAVEANACCOUNT: "Do not have an account?",
  REGISTER: "Register",
  PASSWORD: "Password",
  BUSINESS: "Business",
  INDIVIDUAL: "Particular",
  OPTIONNOTAVAIL: "This option is not available yet",
  ENTERFIRSTNAME: "Enter First Name",
  ENTERLASTNAME: "Enter Last Name",
  BUSINESSHOURS: "Business Hours",
  ADDSHIFT: "Add Shift",
  ADDANOTHERSHIFT: "Add Another Shift",
  UPLOADLICENSEIMAGE: "Upload License Image",
  LICENSEIMAGE: "License Image",
  IDOACCEPT: "I do accept the ",
  CHANGEYOURPASSWORD: "Change Your Password",
  CHANGPASSMODALDES:
    "Shorex needs to verify your identity to reset your password,OTP code sent to you through Email/Phone. Please enter your email/phone to reset password.",
  SENDCODE: "Send Code",
  EnterOTPCODE: "Enter OTP CODE",
  OTPMODALDESC:
    "Shorex needs to verify your identity to reset your password,OTP code sent to you through SMS please enter OTP code below and reset password.",
  RESENDOTP: "Resend OTP",
  ENTERNEWPASSWORD: "Enter New Password?",
  SKIP: "Skip",
  AREYOUSRURELANG: "Are you sure want to switch language?",
  AREYOURSUREACNTDEL: "Are you sure want to delete your account permanently?",
  SUREDELRECYCLE: "Are you sure you want to delete this recycle order?",
  UPDATEORDER: "Update Order",
  customerslocation: "Customers Location",
  validaitonIBAN:
    "Please enter bank name, valid IBAN and account holder name in your profile",
  CONFIRM: "Confirm",
  NOREDDEMPOINTS: "No Redeem Points",
  NODONATEDPOINTS: "No Donated Points",
  NORECYCLEREQUEST: "No Recycle Request",
  PASSWORDCONTAIN11: "Password Contain Atleast 11 Char",
  CARTONPAPER: "Cardboard & paper",
  CARTONPAPERDESC:
    "We kindly ask you to hand in your waste clean and folded or unrolled. Make sure you remove any paper clips, staples, tape or any other material stuck to the paper or cardboard. You can be guided by the following images.Cardboard available for recycling",
  GLASSDESC:
    "We kindly ask you to hand in your waste free of organic waste. Make sure you remove bottle caps, jar lids, any food and drink remains. You can be guided by the following images.Glass available for recycling",
  GLASS: "Glass",
  PLASTIC: "Plastic",
  PLASTICBOTTLE: "Plastic bottle and Pastic caps",
  PLASTICBOTTLEDESC:
    "We kindly ask you to deliver your waste free of organic remains. Please make sure to remove any food or drink left in the bottle; caps are delivered separately. You can be guided by the following images.Plastic available for recycling",
  BEVERAGECAN: "Beverage Can",
  BEVERAGECANDESC:
    "We kindly ask you to hand in your waste without remaining beverage left over. You can be guided by the following pictures.Cans available for recycling",
  HTRCONTENT:
    "Shorex appreciates your loyalty and trust in our recycling system. To enable Shorex to succeed in its mission, we need your help. This section will provide you with information on how to hand in your waste. In addition, we explain the complete process that items go through, how they are collected, segregated and sorted, and then transformed into new products.",
  HOWITCANBEDELIVERED: "How it can be delivered to Shorex",
  AFTERPROCESSINGCARDBOARDPAPER: "After processing the cardboard & paper",
  SAMPLEOFNEWPRO: "Samples of new products",
  AFTERPROCESSINGGLASS:
    "After processing the glass and classified based on the colour",
  AFTERPROCCESSINGPLASTIC:
    "After processing the plastic and classified based on the type & density",
  AFTERPROCESSINGCAN: "After processing the cans",
  YES: "Yes",
  MORNINGSHIFT: "Morning Shift",
  EVENINGSHIFT: "Evening Shift",
  MONDAY: "Monday",
  TUESDAY: "Tuesday",
  WEDNESDAY: "Wednesday",
  THURSDAY: "Thursday",
  FIRDAY: "Friday",
  SATURDAY: "Saturday",
  SUNDAY: "Sunday",
  NOPRODUCTFOUND: "No Product Found",
  BLOCKEDMESSAGE: "You are Blocked by the Admin",
  WTQTTEXT: "Quantity must be greater than 0",
  PLEASESELECTITEM: "Please Select Item",
  MORNINGSLOT: "Morning Slot",
  EVENINGSLOT: "Evening Slot",
  BOTHFIELDSREQ: "Both Fields are Required",
  PLEASESELECTANOTHERDATE: "Please Select Another Date",
};
