export default {
  RECYCLE: "Reciclar",
  HOW_TO_RECYCLE: "Cómo reciclar",
  ECOREWARD: "Eco Puntos",
  HISTORY: "Historial",
  RECYCLEORDER: "Orden de reciclaje",
  SETTING: "   Ajustes   ",
  HOME: "Home",
  NOTIFICATIONS: "Notificaciones",
  PROFILE: "Perfil",
  CONTACTUS: "Contáctanos",
  LANGUAGES: "Idiomas",
  SPANISH: "Español",
  ENGLISH: "English",
  SECURITYSETTING: "Configuración de seguridad",
  CHANGEPASSWORD: "Cambia la contraseña",
  DELETEACCOUNT: "Borrar cuenta",
  PRIVACYPOLICIY: "Política de privacidad",
  BLOCKEDMESSAGE: "Estás bloqueado por el administrador",
  WTQTTEXT: "El valor debe ser mayor que 0",
  TERMCONDITONS: "Términos y condiciones",
  LOGOOUT: "Cerrar sesión",
  ADDREQUEST: "Añadir solicitud",
  CHOOSERECYCLEITEM: "Artículos de reciclaje",
  NEXT: "Siguiente",
  MARKSCHEDULE: "Marcar horario",
  SCHEDULE: "Calendario",
  ONCEONLY: "Por una sola vez",
  MULTIPLEDATES: "Fechas Múltiples",
  MONTHLY: "Mensual",
  ONCEONLYSCHEDULE: "Horario de una sola vez",
  ONCEONLYDESC:
    "Puede seleccionar un horario por día, Ya sea por la mañana o por la tarde.",
  DAY: "Día",
  SELECTSHIFT: "elije jornada",
  SELECTSHIFTSLOT: "elije jornada",
  MORNING: "Mañana",
  EVENING: "Tarde",
  SELECTDATESHIFT: "Seleccionar fecha y turno",
  SELECTSTARTENDTIME: "Seleccione la hora de inicio y finalización",
  PICKUPADDRESSLOCATION: "Dirección y ubicación de recogida",
  UPLOADIMG: "Cargar imagen",
  NOTES: "notas",
  THISISDUMMYTXT: "Este es el texto ficticio",
  PICKUPREQLOCATION: "Lugar de recogida",
  HI: "Hola",
  WELCOMEBACK: "Bienvenido de nuevo,",
  SAVE: "Guardar",
  ORDERCONFIRAMTION: "confirmación de la recogida",
  SELECTEDITEMS: "Artículos seleccionados",
  PICKUPTIME: "Hora de recogida",
  DATE: "Fecha",
  CONFIRMORDER: "Confirmar",
  CONFIRMORDERMODALDESC:
    "Su solicitud de la recogida se generó y se envió al administrador con éxito, nos pondremos en contacto con usted en breve.",
  THANKYOU: "¡Gracias!",
  MULTIPLEDATESSCHEDULE: "Calendario de fechas múltiples",
  MULTIPLEDESC:
    "Puede seleccionar el horario para dos días, Ya sea por la mañana o por la tarde.",
  PLEASESELECTDATETIME: "Seleccione Fecha y hora",
  SELECTMORNINGSTARTENDTIME:
    "Seleccione la hora de inicio y finalización de la mañana",
  MONTHLYSCHEDULE: "Horario Mensual",
  MONTHLYDESC:
    "Puede seleccionar hasta 31 fechas programadas para el mes, Ya sea por la mañana o por la tarde.",
  SETDATE: "Define la fecha",
  PLEASESELECTSTARTEND: "Seleccione la hora de inicio y finalización",
  RECYCLEYOURMULTIPLE: "Recicla tu múltiplo",
  PRODUCTSWITH: "Productos con.",
  EARNEDPOINTS: "Puntos Ganados",
  BALANCE: "Balance",
  CLAIMREWARD: "Canjear",
  CLAIMTHEREWARD: "Canjear",
  ENTERCALIMREWARD: "Cuantos € para canjear?",
  DONATE: "Donar",
  DONATEREWARD: " Cuantos € para donar?",
  REDEEM: "Confirmar",
  CLAIMMODAL:
    "el importe mínimo de la operación de canje es de 10 €, o más con múltiplos de 5 € únicamente.",
  DONATEMODAL:
    "Done para ayudar a las ONG que se preocupan por el medio ambiente.",
  REDEEMPOPUPDESC:
    "Verifique que toda la información   ingresada sea correcta antes de canjear esta cantidad.",
  GOBACK: "Regresa",
  CONTINUE: "Continuar",
  SUCCESSREDEEMMODALDESC:
    " Su solicitud para canjear estos puntos se ha enviado con éxito.",
  ENOUGHBALANCE: "No hay suficientes puntos",
  RECEIVEASMALL: "Recibe un inmenso",
  THANKYOUFOREFFOR: "agradecimiento por ser ecológico.",
  REDEEMPOINTS: "Canjear",
  RECYCLED: "Reciclar",
  FILTER: "Filtrar",
  CLEARFILTER:'Claro Filter',
  SELECTADATE: "Selecciona la fecha",
  TOTALEARNEDPOINTS: "Total de puntos ganados",
  SELECTDATE: "Seleccione fecha",
  EDIT: "Editar",
  DELETE: "Borrar",
  NONOTIFICATIONYET: "No hay notificaciones todavía",
  LOADMORE: "Carga más",
  EMAIL: "Correo electrónico",
  MOBILENO: "Móvil",
  PHONENO: "Número de teléfono",
  PHONE: "Teléfono fijo",
  BUSINESSNAME: "Razón social",
  BUSINESSDEATILS: "Detalles comerciales",
  LICENSECODE: "NIF / DNI / NIE",
  POSTOFFICECODE: "Código Postal",
  ADDRESSANDLCOATION: "Dirección y ubicación",
  BUSINESSCATEGORY: "Categoría del negocio",
  STAFFINCHARGE: "Personal a cargo",
  BANKNAME: "Nombre del banco",
  ACCOUNTTYPE: "Tipo de cuenta",
  ACCOUNTINFORMATION: "Información de la cuenta",
  ACCOUNTHOLDERNAME: "nombre del titular de la cuenta",
  EDITPROFILE: "Editar perfil",
  FIRSTNAME: "Nombre",
  LASTNAME: "Apellido",
  UPDATEPROFILE: "Actualización del perfil",
  UPDATELICENSEIMG: "Actualizar imagen de licencia",
  LICENSEIMAGE: "Imagen de licencia",
  OTHERSTAFF: "Otro personal a cargo",
  FEELFREE: "escríbenos un correo ",
  IBAN: "IBAN",
  CONVENIENCE: "electrónico",
  CHANGEPASSWORD: "¿Cambia la contraseña?",
  CONFIRMPASSWORD: "Confirmar Clave",
  ENTERNEWPASSWORDTORESET: "Introduzca una nueva contraseña para restablecer.",
  NEWPASSWORD: "Nueva contraseña",
  CONFIRMNEWPASSWORD: "Confirmar Clave",
  SUBMIT: "Continuar",
  SUBMITCO:'Enviar',
  DELETEACCOUNTDES:
    "Si no tiene ninguna solicitud de reciclaje, puede eliminar la cuenta.",
  REASONTODELETE: "(Razón para eliminar la cuenta)",
  DELETEMYACCOUNT: "Borrar mi cuenta",
  PRIVACYPOLICY: "Política de privacidad",
  TERMSCONDITION: "Términos y condiciones",
  HELLO: "Hola",
  ENTERYOUREMAIL: "Introduce tu correo electrónico",
  FORGOTPASSWORD: "¿Has olvidado tu contraseña?",
  LOGIN: "Acceder",
  DONTHAVEANACCOUNT: "¿No tiene una cuenta?",
  REGISTER: "Regístrate",
  PASSWORD: "Clave",
  BUSINESS: "Negocio",
  INDIVIDUAL: "Particular",
  OPTIONNOTAVAIL: "Esta opción aún no está disponible",
  ENTERFIRSTNAME: "Ingrese el nombre",
  ENTERLASTNAME: "Introduzca el apellido",
  BUSINESSHOURS: "Jornadas del trabajo",
  ADDSHIFT: "horarios semanales",
  ADDANOTHERSHIFT: "Más horarios semanales",
  UPLOADLICENSEIMAGE: "Imagen del NIF / DNI / NIE",
  IDOACCEPT: "acepto el ",
  CHANGEYOURPASSWORD: "Cambia tu contraseña",
  CHANGPASSMODALDES:
    "Shorex necesita verificar su identidad para restablecer su contraseña, se le envió el código OTP por correo electrónico/teléfono. Ingrese su correo electrónico/teléfono para restablecer la contraseña.",
  SENDCODE: "Enviar código",
  EnterOTPCODE: "Ingrese el CÓDIGO OTP",
  OTPMODALDESC:
    "Shorex necesita verificar su identidad para restablecer su contraseña. Se le envió el código OTP a través de SMS. Ingrese el código OTP a continuación y restablezca la contraseña.",
  RESENDOTP: "Reenviar OTP",
  ENTERNEWPASSWORD: "¿Ingrese nueva clave?",
  SKIP: "Saltar",
  AREYOUSRURELANG: "¿Seguro que quieres cambiar de idioma?",
  AREYOURSUREACNTDEL:
    "¿Está seguro de que desea eliminar su cuenta de forma permanente?",
  SUREDELRECYCLE:
    "¿Está seguro de que desea eliminar este pedido de reciclaje?",
  UPDATEORDER: "Modificar",
  customerslocation: "Ubicación de los clientes",
  validaitonIBAN:
    "Por favor, introduzca el nombre del banco, IBAN válido y el titular de la cuenta en tu perfil",
  CONFIRM: "Confirmar",
  NOREDDEMPOINTS: "No hay puntos canjeados",
  NODONATEDPOINTS: "No hay puntos donados",
  NORECYCLEREQUEST: "No hay solicitudes de reciclaje",
  PASSWORDCONTAIN11: "Das Passwort enthält mindestens 11 Zeichen",
  CARTONPAPER: "Cartón y papel",
  GLASS: "Vidrio",
  GLASSDESC:
    "Te pedimos que entregues tus residuos sin restos orgánicos. Asegúrate de quitar los tapones de las botellas, las tapas de los tarros, cualquier resto de comida o bebida. Puedes guiarte con las siguientes imágenes.Vidrio disponible para reciclar",
  CARTONPAPERDESC:
    "Te pedimos que entregues tus residuos limpios y doblados o desplegados. Asegúrate de eliminar cualquier clip, grapas, cinta adhesiva o cualquier otro tipo de material pegado al papel o al cartón. Puedes guiarte con las siguientes imágenes.Cartón y papel disponible para reciclar",
  PLASTIC: "plástico",
  BEVERAGECAN: "Latas de bebidas",
  PLASTICBOTTLE: "Botellas de plástico y tapones de plástico",
  PLASTICBOTTLEDESC:
    "Te pedimos que entregues tus residuos sin restos orgánicos. Asegúrate de quitar los restos de comida o bebida de la botella; los tapones se entregan por separado. Puedes guiarte por las siguientes imágenes.Plástico disponible para reciclar",
  BEVERAGECANDESC:
    "Te pedimos que entregues tus residuos sin restos de bebida. Puede guiarse por las siguientes imágenes.Latas disponibles para reciclar",
  HTRCONTENT:
    "Shorex agradece tu lealtad y confianza en nuestro sistema de reciclaje. Para que Shorex pueda cumplir con éxito su misión necesitamos tu ayuda. Esta página te dará información para que sepas cómo entregar tus resíduos. Además, te explicamos el proceso completo por el que pasan los artículos, cómo se recogen, se segregan y clasifican, para luego transformarlos en nuevos productos.    ",
  PLASTICBOTTLE: "Botellas de plástico y tapones de plástico",
  PLASTICBOTTLEDESC:
    "Te pedimos que entregues tus residuos sin restos orgánicos. Asegúrate de quitar los restos de comida o bebida de la botella; los tapones se entregan por separado. Puedes guiarte por las siguientes imágenes.Plástico disponible para reciclar",
  BEVERAGECAN: "Latas de bebidas",
  BEVERAGECANSDESC:
    "Te pedimos que entregues tus residuos sin restos de bebida. Puede guiarse por las siguientes imágenes.Latas disponibles para reciclar",
    YES: "sí",
  HOWITCANBEDELIVERED: "Cómo se puede entregar a Shorex",
  AFTERPROCESSINGCARDBOARDPAPER: "Después de procesar el Cartón y papel",
  SAMPLEOFNEWPRO: "Muestras de nuevos productos",
  AFTERPROCESSINGGLASS: "Después de procesar el vidrio ",
  AFTERPROCCESSINGPLASTIC: "Después de procesar el plástico",
  AFTERPROCESSINGCAN: "Después de procesar las latas",
  MORNINGSHIFT: "Jornada de mañana",
  EVENINGSHIFT: "Jornada de tarde",
  MONDAY: "lunes",
  TUESDAY: "martes",
  WEDNESDAY: "miércoles",
  THURSDAY: "jueves",
  FIRDAY: "viernes",
  SATURDAY: "sábado",
  SUNDAY: "domingo",
  NOPRODUCTFOUND: "No se encontró ningún producto",
  PLEASESELECTITEM:'Elije un artículo',
  MORNINGSLOT:'Mañana',
  EVENINGSLOT:'Tarde',
  BOTHFIELDSREQ:'Ambos campos son obligatorios',
  PLEASESELECTANOTHERDATE:"Seleccione otra fecha"
};
